### ISSUE TITLE
Dropped support for PHP 5.3.*?

### ISSUE THREAD

**Issue by mefiblogger** [InterNations/SolrUtils#4]
Hello!

We are using InterNations/SolrUtils in our projects, but unfortunately (mainly by historical reasons, of course :smile:) we must use PHP 5.3.10.

As this new release broke the build, we are now using SolrUtils 0.4.3, which is the last version supporting PHP 5.3.

Also, I think this is a major update, if you are using semver (because it is absolutely lost backward compatibility).

Is there any chance, that you consider supporting PHP 5.3, or we should deal with it?

Thanks!
Mefi

**Comment by lstrojny** [comment]
v0.5.0 is the first version to remove support for 5.3. 5.3 is now roughly 1000 years old and doesn't even have security patches anymore. Reason I did it is that dependencies of SolrUtils nowadays require at least >=5.4.

**Comment by mefiblogger** [comment]
I see, thank you for your answer.

However, If you don't mind, let me suggest some improvements:

- you should mark the required [minimum PHP version](https://getcomposer.org/doc/04-schema.md#package-links) in your composer.json file.
- Also, if you are using semantic versioning, then you should really bump the version to 1.0.0, because this is a major update in which you made incompatible API changes.

Regards,
Mefi

**Comment by lstrojny** [comment]
@mefiblogger marking the minimum PHP version makes a lot of sense, thanks. According to semantic versioning, this is applicable: "Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable."

**Comment by mefiblogger** [comment]
Thanks, I forgot this zero version convention.
